use std::io::Error;


pub async fn generate_base_proof() -> Result<(), Error> {
    unimplemented!()
}

pub async fn generate_reccursive_proof() -> Result<(), Error> {
    unimplemented!()
}